### ISSUE TITLE
date column format

### ISSUE THREAD

**Issue by ZNevzz** [ZNClub-PA-ML-AI/Research-Platform-Stock-Market#2]
1. date format in twitter+quandl merged data is M-D-Y
2. date format in news +quandl merged data is Y-M-D
3. Highcharts requires sorted data in the format of Y-M-D
_So start merging again & keep Y-M-D as the fornat_

**(Hint: When u open any csv file in Microsoft Excel, do not save changes as Excel changes date format to M-D-Y automatically**

**Comment by Crystal21** [comment]
Done. refer final_dataset_twitter.csv for hybrid method prediction
